### ISSUE TITLE
KERNEL PANIC AFETER UPDATE

### ISSUE THREAD

**Issue by wifi75** [AuxXxilium/AuxXxilium#1]
Hypervisor : proxmox
DSM: ds1621+

hello i have tryed to update loader from 22.12.26 to new version 23.01.09
version 22.12.26 worked perfectly!

this is the error from console
![image](https://user-images.githubusercontent.com/31816231/211492258-390a422d-f1c6-4bb8-aedc-d1aa2e709fac.png)

what can I do?

**Comment by AuxXxilium** [comment]
Go back to 22.12.26. Is the only thing you can do. Am 10.01.2023 um 08:52 schrieb wifi75 ***@***.***>:﻿
Hypervisor : proxmox
DSM: ds1621+
hello i have tryed to update loader from 22.12.26 to new version 23.01.09
version 22.12.26 worked perfectly!

this is the error from console

what can I do?

**Comment by AuxXxilium** [comment]
And please provide the complete log file.

**Comment by wifi75** [comment]
which log do you need?

**Comment by AuxXxilium** [comment]
Serial outputAm 10.01.2023 um 09:02 schrieb wifi75 ***@***.***>:﻿
which log do you need?

**Comment by AuxXxilium** [comment]
serial output. but you can look into addons. i moved 9p modules back to addons. so i think you need this for proxmox.

**Comment by wifi75** [comment]
9p module it is loaded, but I have some error:
![image](https://user-images.githubusercontent.com/31816231/211554379-9358150e-6977-45ae-92c5-0fd642aa2076.png)

**Comment by AuxXxilium** [comment]
ok i see it in first shown line of log. will fix it today. Am 10.01.2023 um 13:42 schrieb wifi75 ***@***.***>:﻿
9p module it is loaded, but I have some error:

**Comment by wifi75** [comment]
ok when you're ready I'll do more tests...

**Comment by AuxXxilium** [comment]
should be fixed with latest release. please try again.

**Comment by wifi75** [comment]
hello, after update:
![image](https://user-images.githubusercontent.com/31816231/211752981-8024d104-6d90-4c44-8485-284d7121a3b8.png)

**Comment by AuxXxilium** [comment]
please remove direct boot in loader

**Comment by wifi75** [comment]
boot was already false, i set it to true then false again. on boot it worked.
perhaps the update spawns that bad joke.

I wanted to inform you that this message appears, what does it mean?

![image](https://user-images.githubusercontent.com/31816231/211758678-935ef0d5-d3b4-4893-b062-291512616e65.png)

**Comment by AuxXxilium** [comment]
this message is nothing to worry about. if you want try the version without "a" in the end.

**Comment by AuxXxilium** [comment]
> boot was already false, i set it to true then false again. on boot it worked. perhaps the update spawns that bad joke.
> 
> I wanted to inform you that this message appears, what does it mean?
> 
> ![image](https://user-images.githubusercontent.com/31816231/211758678-935ef0d5-d3b4-4893-b062-291512616e65.png)

This message will be shown, if your config is not matching the hardware. because in your config are more or less mac address than your hardware has adapter. in your case you have 2 network adapter and only 1 custom mac in config, i guess.
