### ISSUE TITLE
Boot issue - stuck at "Loading initramfs" - Acer Easystore H341

### ISSUE THREAD

**Issue by cherberg** [AuxXxilium/AuxXxilium#2]
Dear Developer,

I am trying to revive an old Acer H341. I dowloaded the image for the Arc Automated Redpill Loader, burned the image to a 2GB USB stick selected the stick in den Boot menu in BIOS and booted the device. Unfortunately I only get as far as "Loading initramfs..." then the screen turns off and nothing else happens.
![image](https://user-images.githubusercontent.com/8701752/212752129-e053c5a1-6701-4afb-841e-1c5c4c348ce5.png)

The BIOS has only very limited features, I followed all suggestion from the help section. I tried different USB image burners like Balena Etcher and Rufus.

Any help to be able to benefit from this great development is highly appreciated.
br CH

**Comment by AuxXxilium** [comment]
Please wait for updated version. v23.01.16Am 16.01.2023 um 20:22 schrieb cherberg ***@***.***>:﻿
Dear Developer,
I am trying to revive an old Acer H341. I dowloaded the image for the Arc Automated Redpill Loader, burned the image to a 2GB USB stick selected the stick in den Boot menu in BIOS and booted the device. Unfortunately I only get as far as "Loading initramfs..." then the screen turns off and nothing else happens.

The BIOS has only very limited features, I followed all suggestion from the help section. I tried different USB image burners like Balena Etcher and Rufus.
Any help to be able to benefit from this great development is highly appreciated.
br CH
