### ISSUE TITLE
failed to create the cluster 

### ISSUE THREAD

**Issue by yossiyemin** [AuxXxilium/AuxXxilium#4]
Hello, I'm trying to install vm and I get the following error failed to create the cluster

**Comment by AuxXxilium** [comment]
no further informations and this issue doesn't belong to arc. look like issue of your vm.

**Comment by yossiyemin** [comment]
> no further informations and this issue doesn't belong to arc. look like issue of your vm.

I'll rephrase, I'm using your bootloader ds923 +. The installation succeeds perfectly - when I try to use the virtual machine manager in synology I get the error, from a Google search this is a known error
